name: "UAT Build"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  uat-build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.x
          cache: yarn

      - name: Install
        run: yarn

      - name: Build
        run: yarn build
        env:
          REACT_APP_MAIN_URL: ${{ secrets.REACT_APP_MAIN_URL }}
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: akasabuild
          path: akasabuild
          retention-days: 1

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: akasabuild
